//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resort_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityAmenityTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacilityAmenityTran()
        {
            this.CustomerTrans = new HashSet<CustomerTran>();
        }
    
        public int LuxuryID { get; set; }
        public string LuxuryName { get; set; }
        public int AmenityID { get; set; }
        public Nullable<long> LuxuryCost { get; set; }
    
        public virtual AmenitiesMaster AmenitiesMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTran> CustomerTrans { get; set; }
    }
}
