//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resort_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityAmenityTran
    {
        public int LuxuryID { get; set; }
        public string LuxuryName { get; set; }
        public int AmenityID { get; set; }
        public Nullable<long> LuxuryCost { get; set; }
    
        public virtual AmenitiesMaster AmenitiesMaster { get; set; }
    }
}
